name: Build FastAPI Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::792171318913:role/FredBallApiGitHubActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Poetry tools
        run: poetry self add poetry-plugin-lambda-build

      - name: Package application into ZIP
        run: poetry build-lambda

      - name: Upload ZIP to S3
        run: aws s3 cp package.zip s3://${{ vars.S3_BUCKET }}/package.zip

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name ${{ vars.LAMBDA_FUNCTION }} \
            --s3-bucket ${{ vars.S3_BUCKET }} \
            --s3-key package.zip
